version: '3'

services:
  keycloak:
    image: keycloak/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
